yichya/luci-app-xray

Makefile
root/www/luci-static/resources/view/xray.js

xtls splice

---

Makefile

feat: allow to determine whether to use proxychains during build

---

Makefile
root/etc/hotplug.d/iface/01-transparent-proxy

feat: build xray from source

---

Makefile
README.md
root/etc/init.d/xray
root/usr/share/xray/gen_config.lua
root/usr/share/xray/infinite_retry
root/www/luci-static/resources/view/xray.js

also make init script infinite retry optional

feat: add gRPC Transport settings

---

root/www/luci-static/resources/view/xray.js

接受更多DNS服务器格式。
Ref: [内置DNS服务器 :: Project X](https://xtls.github.io/config/base/dns/)

feat: Accept more DNS server formats

---

Makefile
README.md

This breaks a lot of things for good

feat: compatible with OpenWrt official Xray-core by replacing its files

---

root/usr/share/xray/gen_config.lua
root/www/luci-static/resources/view/xray.js

feat:support sniffing routeonly

---

root/www/luci-static/resources/view/xray.js

修改内容：
1. 资源文件显示单位改为MB
2. 资源检查状态对i18n友好

chore:show resource file size changed to MB & friendly for i18n

---

root/www/luci-static/resources/view/xray.js

修复了当禁用Tproxy再重新打开后UDP服务器变为列表第一个服务器的问题

fix:when disable tproxy,udp server become list first server

---

Makefile
root/usr/share/xray/gen_config.lua
root/www/luci-static/resources/view/xray.js

feat: multiple geoip direct code

---

Makefile
README.md
root/usr/share/xray/firewall_include.uc

Even for reserved addresses. Xray may not forward those requests so that manner may be changed later.

fix: make sure forwarded IPs are always forwarded to Xray

---

root/usr/share/xray/gen_config.lua

fix ipv6 leak

---

Makefile
README.md
root/usr/share/xray/gen_config.lua
root/www/luci-static/resources/view/xray.js

feat: dialer proxy

---

Makefile
README.md
root/usr/share/xray/firewall_include.uc

feat: use goto instead of jump in nftables rules

---

Makefile
root/www/luci-static/resources/view/xray.js

fix: mark HTTP Host required

---

Makefile
README.md
root/usr/share/xray/gen_config.uc
root/www/luci-static/resources/view/xray.js

Will be merged after next Xray-core release.
Currently only implemented in ucode, which means OpenWrt 22.03 versions (or master branch) and fw4 is required. Support for previous versions (19.07 / 21.02) will be added later. (If time permits, maybe before this feature gets merged)

feat: experimental REALITY support

---

root/etc/config/xray
root/usr/share/xray/gen_config.lua
root/usr/share/xray/gen_config.uc
root/www/luci-static/resources/view/xray.js

feat: add Bittorrent Direct option

---

fw3/root/usr/share/xray/gen_config.lua
fw4/root/usr/share/xray/gen_config.uc

fix: change order of bridge rules

---

README.md
core/root/etc/config/xray_core
core/root/usr/share/xray/firewall_include.ut
core/root/www/luci-static/resources/view/xray/core.js
core/root/www/luci-static/resources/view/xray/preview.js

feat: better network interface control

---

.github/workflows/build-release.yml
README.md
core/Makefile
core/root/www/luci-static/resources/view/xray/preview.js
status/Makefile

chore: bump version

---

core/root/usr/share/xray/common/tls.mjs

Try to fix deserialization issue

Update tls.mjs to eliminate deserialization failure
